#!/bin/bash
# see https://qiita.com/hidache/items/7dbf0eba2f36f5e1a447
#
# DEPRECATED USE peco_cd_with_ghq
#

# ghq のプロジェクトに移動
function ghql() {
  local src=$(ghq list --full-path | peco --query "$LBUFFER")
  if [ -n "$src" ]; then
    cd ${src}
  fi
}

bind -x '"\201": ghql'
bind '"\C-]":"\201\C-m"'
